---
functional:
  - Сайт должен поддерживать режим игры с другим игроком
  - Сайт должен поддерживать режим игры с ботом
  - Сайт должен предоставлять возможность пригласить друга по уникальной ссылке
  - Сайт должен обеспечивать соревнование двух игроков в решении задач на скорость
  - Сайт должен позволять выбирать конкретную задачу при создании игры
  
  - Сайт должен предоставлять различные задачи для решения
  - Оба игрока видят друг у друга редактор с кодом и вывод тестов
  - Оба игрока могут менять язык программирования во время решения
  - Пользователь должен иметь возможность переключить язык интерфейса
 
  - Пользователь должен иметь возможность выбрать уровень сложности игры
  - Другие пользователи должны иметь возможность следить за ходом игры
  - Сайт должен предоставлять чат для общения зарегистрированных пользователей
  - Система должна сохранять записи завершенных игр для последующего просмотра
  - Система должна вести рейтинг игроков на основе результатов игр за неделю, за месяц и за всё время

  - Сайт должен предоставлять редактор кода в виде проигрыватель с функционалом паузы и перемотки

non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
  - Сайт должен быть доступен на различных устройствах
  - Сайт должен иметь локализацию на русский и английский языки
implicit:
  - Интерфейс сайта должен иметь адаптивный дизайн и быть интуитивно понятным для любого пользователя
  - При слабом интернет соединении, должна выводится основная информация сайта
  - Должна присутствовать защита от XSS
  - Личные данные пользователя должны быть защищены
