---
functional:
  - Сайт должен поддерживать режим игры с другим игроком
  - Сайт должен поддерживать режим игры с ботом
  - Сайт должен предоставлять возможность пригласить друга по уникальной ссылке
  - Сайт должен обеспечивать соревнование двух игроков в решении задач на скорость
  - Сайт должен позволять выбирать конкретную задачу при создании игры
  
  - Сайт должен предоставлять различные задачи для решения
  - Оба игрока видят друг у друга редактор с кодом и вывод тестов
  - Оба игрока могут менять язык программирования во время решения
  - Пользователь должен иметь возможность переключить язык интерфейса
 
  - Пользователь должен иметь возможность выбрать уровень сложности игры
  - Другие пользователи должны иметь возможность следить за ходом игры
  - Сайт должен предоставлять чат для общения зарегистрированных пользователей
  - Система должна сохранять записи завершенных игр для последующего просмотра
  - Система должен предоставлять редактор кода в виде проигрывателя с функционалом паузы и перемотки
  - Система должна вести рейтинг игроков на основе результатов игр за неделю, за месяц и за всё время

  - Система должна предоставлять форму регистрации с email и паролем
  - Система должна требовать подтверждения email адреса перед активацией аккаунта
  - Система должна проверять уникальность email и имени пользователя
  - Система должна предоставлять возможность восстановления пароля через подтверждение по email
  
  - Система должна позволять пользователям редактировать основные данные профиля, включая имя, почту и язык программирования
  - Система должна отображать пользователю его персональную статистику игр, текущий рейтинг и количество сыгранных игр

  - В чате на главной странице должна быть возможность отправлять сообщения и смайлики
  - В форме чата должно выводится количество пользователей онлайн и их статус (Watching, Playing, Lobby, Online)
  - В форме чата на главной странице должна быть возможность отправить приватное сообщение пользователю, который сейчас онлайн
  - В форме чата на главной странице должна быть возможность отправить приглашение на сражение пользователю, который сейчас онлайн
  
  - В чате редактора кода должна быть возможность отправлять сообщения и смайлики
  - Во время сражения с другим пользователем должна быть возможность открыть историю сражения в виде плеера
  - Во время сражения с другим пользователем должна быть возможность вернуться на главную страницу сайта

non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Интерфейс редактора кода должен поддерживать 10+ языков программирования
  - Переключение между языками программирования должно происходить без потери написанного кода
  
  - Сайт должен быть безопасным и защищать данные пользователя
  - Система должна предотвращать попытки вмешательства в чужой аккаунт
  - Система должна предотвращать попытки пользователя скопировать свой код или вставить чужой код в свой редактор

  - Сайт должен быть удобным на мобильном устройстве
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Сайт должен быть доступен на различных устройствах
  - Сайт должен иметь локализацию на русский и английский языки

  - Система должна обеспечивать безопасное хранение паролей пользователей
  - Система должна требовать от пользователей установки пароля длиной не менее 8 символов с использованием специальных символов
  - Система должна отправлять письмо для подтверждения email
  
implicit:
  - Интерфейс сайта должен иметь адаптивный дизайн и быть интуитивно понятным для любого пользователя
  - При слабом интернет соединении, должна выводится основная информация сайта
  - Должна присутствовать защита от XSS
  - Личные данные пользователя должны быть защищены
  - Уровни сложности должны быть сбалансированы и соответствовать заявленным категориям
  - Должна быть возможность поделиться ссылкой на записанную завершенную игру
  - В плеере просмотре завершенной игры должна быть возможность менять скорость воспроизведения
  - При регистрации должна быть возможность войти, используя учетные записи других ресурсов (Github, Discord)
  - Должна выполняться синхронизация со стронными ресурсами (Github, Discord), использованных для регистрации пользователя
